export const COLLEGES = [
  "Model Institute of Engineering and Technology, Jammu",
  "BITS Pilani, Pilani",
  "Vellore Institute of Technology (VIT), Vellore",
  "SRM Institute of Science and Technology, Chennai",
  "Manipal Institute of Technology, Manipal",
  "Thapar Institute of Engineering and Technology, Patiala",
  "Delhi Technological University (DTU), New Delhi",
  "Jadavpur University, Kolkata",
  "Anna University, Chennai",
  "Amity University, Noida",
  "Jamia Millia Islamia, New Delhi",
  "Aligarh Muslim University, Aligarh",
  "Siksha 'O' Anusandhan, Bhubaneswar",
  "Kalinga Institute of Industrial Technology (KIIT), Bhubaneswar",
  "Koneru Lakshmaiah Education Foundation (KL University), Vaddeswaram",
  "Amrita Vishwa Vidyapeetham, Coimbatore",
  "Lovely Professional University (LPU), Phagwara",
  "Chandigarh University, Mohali",
  "Symbiosis Institute of Technology, Pune",
  "SASTRA University, Thanjavur",
  "Sri Sivasubramaniya Nadar (SSN) College of Engineering, Chennai",
  "UPES, Dehradun",
  "IIIT Hyderabad, Hyderabad",
  "Institute of Chemical Technology (ICT), Mumbai",
  "Chitkara University, Patiala",
];